### ISSUE TITLE
Regularly crashes on Fedora Silverblue 40

### ISSUE THREAD

**Issue by shawnyeager** [DeedleFake/trayscale#163]
First, thanks for building this. 

I installed a few days ago on a new installation of Fedora Silverblue 40. It seemed to run well initially, but now, it regularly, quietly crashes. I only know when I notice the system tray icon is gone.

Happy to provide any logs or other info, if helpful.

**Comment by DeedleFake** [comment]
I will definitely need logs to see what the problem is. If you installed the Flatpak version, you can run it from the command line using `dev.deedles.Trayscale`.

**Comment by shawnyeager** [comment]
I'm running v0.13.4 via Flathub. `dev.needles.Trayscale` doesn't resolve for me with my current paths. I'm new to Flatpaks. Could you point me to where I can explicitly ref?

**Comment by DeedleFake** [comment]
> I'm running v0.13.4 via Flathub. `dev.needles.Trayscale` doesn't resolve for me with my current paths. I'm new to Flatpaks. Could you point me to where I can explicitly ref?

You've got a typo there. It's `dev.deedles.Trayscale`. Along with just running that directly, you can use `flatpak run dev.deedles.Trayscale`.

**Comment by shawnyeager** [comment]
Thanks. Typo in my comment, not in my CLI. It will not resolve. Running `flatpak run dev.deedles.Trayscale`, I immediately see this. Unrelated?

```
shawn@carbon:~$ flatpak run dev.deedles.Trayscale
2024/09/09 12:37:44 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2024/09/09 12:37:44 ERROR adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed glib_old_log_api=1 priority=4 glib_domain=Adwaita
```

**Comment by shawnyeager** [comment]
A minute later:

```
** (process:10122): WARNING **: 12:38:46.295: Invalid client serial
panic: dbus: connection closed by user [recovered]
        panic: closure error: unexpected panic caught: dbus: connection closed by user

        Closure added at:
                github.com/diamondburned/gotk4/pkg/glib/v2.IdleAdd at github.com/diamondburned/gotk4/pkg@v0.3.1/glib/v2/glib.go:33679
                deedles.dev/trayscale/internal/ui.(*App).Run.func1 at deedles.dev/trayscale/internal/ui/app.go:402
                deedles.dev/trayscale/internal/tsutil.(*Poller).Run at deedles.dev/trayscale/internal/tsutil/poller.go:119

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc00039e540, {0x1f45128, 0x1b}, {0xc00004d728, 0x1, 0x1})
        github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00039e540)
        github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:122 +0xbc
panic({0x1c14000?, 0x3982710?})
        runtime/panic.go:785 +0x132
github.com/godbus/dbus/v5/prop.(*Properties).SetMust(0xc0002d8f00, {0x1f4334e, 0x1a}, {0x1f304e8, 0xa}, {0x1b72b40, 0xc00036a078})
        github.com/godbus/dbus/v5@v5.1.1-0.20230522191255-76236955d466/prop/prop.go:346 +0xeb
fyne.io/systray.SetIcon({0x39f2720?, 0x578d13?, 0xc00004da18?})
        fyne.io/systray@v1.11.0/systray_unix.go:62 +0x1e6
deedles.dev/trayscale/internal/tray.(*Tray).Update(0xc000098040, {0xc0004b6f70, 0xc0003da000, {0x0, 0x0, 0x0}})
        deedles.dev/trayscale/internal/tray/tray.go:79 +0x13c
deedles.dev/trayscale/internal/ui.(*App).update(0xc000190000, {0xc0004b6f70, 0xc0003da000, {0x0, 0x0, 0x0}})
        deedles.dev/trayscale/internal/ui/app.go:165 +0xce
deedles.dev/trayscale/internal/ui.(*App).Run.func1.1()
        deedles.dev/trayscale/internal/ui/app.go:402 +0x2b
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_sourceFunc(0x100c)
        github.com/diamondburned/gotk4/pkg@v0.3.1/core/glib/glib.go:352 +0xd9
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x353d1ed0, 0x1, 0x35550590)
        _cgo_gotypes.go:14091 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x353d1ed0, 0x1, 0x35550590)
        github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc00019e000, {0xc000122050, 0x1, 0x1})
        github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1
deedles.dev/trayscale/internal/ui.(*App).Run(0xc000190000, {0x21be9e8?, 0xc0002d8d80?})
        deedles.dev/trayscale/internal/ui/app.go:411 +0x2df
main.main()
        deedles.dev/trayscale/cmd/trayscale/trayscale.go:49 +0xae
```

**Comment by DeedleFake** [comment]
Looks like it's the same as #160.

**Comment by shawnyeager** [comment]
I'm also seeing what looks like very high memory consumption. 

![CleanShot 2024-09-09 at 14 39 05@2x](https://github.com/user-attachments/assets/4d04e194-e88e-4f52-890f-1d08cfaee9d9)

**Comment by jonase0202** [comment]
did you find a solution?

**Comment by shawnyeager** [comment]
@jonase0202 I did not. No shade on this project, but I switched to [Tailscale QS](https://github.com/joaophi/tailscale-gnome-qs), and it's been smooth.

**Comment by Jacalz** [comment]
I can not replicate this on Fedora Silverblue 41. Works great on my end
